func printBanner(_ day: String){
    print("*--------------------*")
    print("*  Day \(day)            *")
    print("*--------------------*")
}
printBanner("01")
day01()
printBanner("02")
day02()
printBanner("03")
day03()
printBanner("04")
day04()
printBanner("05")
day05()
printBanner("06")
day06()